"""Pieces every generated report shares: the evidence block and the header."""

from __future__ import annotations

from dataclasses import dataclass

from airline_disruption.reporting.inputs import (
    CALIBRATION_SELECTED_PATH, CONSUMED_PATH, FINAL_DECISION_PATH, Inputs, MissingInput,
)

PROJECT_TITLE = "Airline Network Disruption Intelligence: Delay Prediction, Propagation, Recovery and Network Resilience"
POSITIONING = ("This is an advanced portfolio study for Data Science, applied science, forecasting, operations research, "
               "decision science, transportation analytics and aviation analytics roles. It is a retrospective analysis of "
               "flight-level records. It is not an airline operating system, a dispatch or control tool, a real-time "
               "system or a production service.")
NOT_SUPPORTED = (
    "weather or any other cause of a delay (the data holds no weather and no cause for the flights scored here)",
    "aircraft or tail-number propagation (the source has no usable tail identifier, so no aircraft sequence is built)",
    "causal statements about airports, carriers, routes or schedules (every result is an association)",
    "real airline costs, savings or operating decisions (utility figures are illustrative penalty units)",
    "any claim about flights after 2023-08-31, or about other airlines or countries",
)


# Case studies the project requires that need data beyond the final-test tables. A path is listed as "not built" until its table exists.
CASE_STUDY_FILES = {
    "large regression errors (arrival-delay regression has no stored per-flight predictions, and no regression model was locked)": "reports/tables/regression_large_error_cases.csv",
    "airport episodes with fast and slow recovery": "reports/tables/airport_recovery_episode_cases.csv",
}


def missing_case_studies(inp: Inputs) -> list[str]:
    """Descriptions of the required case studies whose table does not exist."""
    return [text for text, path in CASE_STUDY_FILES.items() if not inp.path(path).exists()]


@dataclass
class Evidence:
    """What ties a report to the single locked final test."""
    decision: dict      # reports/tables/phase7b_final_decision.json
    lock: dict          # the sealed lock
    marker: dict        # reports/final/final_test_consumed.json
    selected: dict      # configs/calibration_selected.json
    smoke: bool

    @property
    def lock_sha(self) -> str:
        return self.lock["lock_sha256"]

    def target(self, name: str) -> dict:
        return self.decision["targets"][name]

    def locked(self, name: str) -> dict:
        return self.lock["targets"][name]


def load_evidence(inp: Inputs) -> Evidence:
    """Load the lock, the marker and the final decision, and stop unless they agree with each other."""
    decision = inp.json(FINAL_DECISION_PATH, required=True)
    lock = inp.json(inp.lock_path, required=True)
    marker = inp.json(CONSUMED_PATH, required=True)
    selected = inp.json(CALIBRATION_SELECTED_PATH, required=True)
    hashes = {"lock file": lock.get("lock_sha256"), "final decision": decision.get("lock_sha256"), "consumed marker": marker.get("lock_sha256")}
    if len(set(hashes.values())) != 1 or None in hashes.values():
        raise MissingInput(f"the lock hashes do not agree, so these tables are not from one locked test: {hashes}")
    if not decision.get("final_test_used"):
        raise MissingInput("the final decision file says the final test was not used")
    smoke = bool(lock.get("smoke")) or bool(inp.tag)
    return Evidence(decision=decision, lock=lock, marker=marker, selected=selected, smoke=smoke)


def header(title: str, inp: Inputs, ev: Evidence) -> str:
    lines = [f"# {title}", "", f"{PROJECT_TITLE}", "", POSITIONING, ""]
    if ev.smoke:
        lines += ["> **TEST BUILD from smoke tables. The numbers are not results.**", ""]
    lines += [
        f"Generated by `scripts/build_phase7_reports.py` from the result tables listed at the end. Every number comes from those files.",
        "",
        f"The final test period (2023-01-01 to 2023-08-31) was scored once, under protocol lock `{ev.lock_sha[:16]}` "
        f"(first run {ev.marker.get('first_run_utc', 'unknown')}). The lock was sealed before any 2023 row was read.",
    ]
    return "\n".join(lines)


def not_supported_section() -> str:
    lines = ["## What the evidence does not support", ""]
    lines += [f"- {item}" for item in NOT_SUPPORTED]
    return "\n".join(lines)


def inputs_section(inp: Inputs) -> str:
    lines = ["## Inputs", "", "Files read to build this report (SHA-256 of each is in `reports/tables/phase7_reports_manifest.json`):", ""]
    lines += [f"- `{path}`" for path in sorted(inp.used)]
    if inp.missing:
        lines += ["", "Files that were looked for and not found. The sections that need them are shortened or left out:", ""]
        lines += [f"- `{path}`" for path in sorted(inp.missing)]
    else:
        lines += ["", "Every file the builder looked for was found."]
    return "\n".join(lines)
