"""README.md for the repository (Phase 7B, Step 15).

The README follows the layout of a recruiter-friendly portfolio README: what the project is, the outcome in one table, plain-word
definitions, data, method, results, repository layout, reproduction, limits and licence. It is written in short, plain sentences so a
school student and a working data scientist can both follow it.

Every number comes from the same result tables as the other reports. Static text is limited to the project design, which does not
change with a result. A file or figure is linked only if it exists when the README is built.
"""

from __future__ import annotations

import pandas as pd

from airline_disruption.reporting import facts
from airline_disruption.reporting.calibration_report import CAPACITY_ORDER, _order
from airline_disruption.reporting.common import NOT_SUPPORTED, PROJECT_TITLE, POSITIONING, Evidence
from airline_disruption.reporting.inputs import Inputs
from airline_disruption.reporting.selection_report import cancel_outcome_positive, failed_claims, locked_scorer_row
from airline_disruption.reporting.technical_report import QUESTIONS
from airline_disruption.reporting.text import bullets, interval, join_sections, md_table, num, pct, whole

SEVERE, CANCEL = "severe_delay_120", "cancelled"
MARKER = "<!-- generated by scripts/build_phase7_reports.py -->"
REPO_NAME = "airline-network-disruption-intelligence"
KAGGLE_URL = "https://www.kaggle.com/datasets/patrickzel/flight-delay-and-cancellation-dataset-2019-2023"

REPORTS = (
    ("final_technical_report.md", "The whole study in one document"),
    ("final_model_selection_report.md", "Which model was chosen, which were rejected, and why"),
    ("calibration_and_alert_policy_report.md", "How reliable the probabilities are, and the what-if review lists"),
    ("explainability_report.md", "What the model uses to make its predictions (SHAP)"),
    ("error_analysis_report.md", "Where the model fails: by period, hour, carrier, airport and delay size"),
    ("network_resilience_report.md", "The airport and route network"),
    ("survival_recovery_report.md", "How long airport disruption episodes last"),
    ("propagation_report.md", "How disruption at airports and routes is linked over time (not aircraft-level)"),
)

BUILT_HERE = frozenset(name for name, _ in REPORTS[:5])   # written by the same run, so they exist by the time the README is read

FIGURES = (
    ("final_pr_curve_severe_delay_120.png", "Precision-recall curve on the 2023 final test"),
    ("final_calibration_curve_severe_delay_120.png", "Reliability of the probabilities on the 2023 final test"),
    ("final_review_capacity_severe_delay_120.png", "Review capacity on the 2023 final test"),
    ("shap_summary.png", "SHAP summary on 2022 validation data (associations, not causes)"),
    ("local_flight_explanation.png", "One local explanation"),
    ("kaplan_meier_recovery.png", "How long airport disruption episodes last (Kaplan-Meier)"),
    ("airport_network.png", "Airport network"),
    ("centrality_vs_disruption.png", "Network centrality against disruption"),
)

LAYOUT = (
    ("configs/", "Settings for the analysis, saved as versioned files"),
    ("docs/", "Data card, method notes and the decision log"),
    ("reports/evaluation/", "The written reports"),
    ("reports/tables/", "Small result tables and the final decision record"),
    ("reports/figures/", "Charts used in the reports"),
    ("reports/final/", "The sealed final-test lock and the record that the test was used"),
    ("scripts/", "One command per step, plus the report builder and the repository check"),
    ("src/airline_disruption/", "The reusable code: features, validation, models, calibration, explanation, reporting"),
    ("tests/", "Automatic tests, including leakage, timestamp, date-split, calibration and metric tests"),
)

PLAIN_SCORERS = {
    "baseline_prevalence": "overall rate", "baseline_carrier_rate": "carrier history", "baseline_origin_rate": "origin airport history",
    "baseline_destination_rate": "destination airport history", "baseline_route_rate": "route history",
}
PLAIN_CLAIMS = {
    "C1_skill_over_chance": "ranks better than chance",
    "C2_beats_history": "beats the strongest history rule",
    "C3_ranking_not_only_seasonal": "still works when flights are ranked inside each day",
}
PLAIN_METHODS = {"uncalibrated": "no calibration", "platt": "Platt scaling", "isotonic": "isotonic regression"}
METHOD_GLOSS = {"platt": "Platt scaling (a sigmoid curve)", "isotonic": "isotonic regression (a step-shaped curve)", "uncalibrated": "no calibration"}

GLOSSARY = (
    "**Severe delay**: the flight lands 120 minutes or more after its planned arrival time. This line is a project choice, not an official rule.",
    "**Prediction time**: 2 hours before the planned departure. The model may use only what is known by then.",
    "**Leakage**: using information that was not known at prediction time. It makes results look better than they are.",
    "**Date-based split**: train on earlier dates and test on later dates, as in real use. Flights are never shuffled across time.",
    "**Baseline**: a simple rule, such as a carrier's past delay rate. A model must beat it to be worth using.",
    "**PR-AUC**: a score from 0 to 1 for how well a model puts rare events at the top of a ranked list. Random ranking scores about the event rate.",
    "**Lift**: PR-AUC divided by the event rate. A lift of 1 means no better than chance.",
    "**Precision and recall**: precision is the share of flagged flights that were really delayed. Recall is the share of all delayed flights that were flagged.",
    "**Calibration**: whether a predicted 5% chance really happens about 5% of the time.",
    "**SHAP**: a method that splits one prediction into the part each feature added. It describes the model, not the real world.",
)


def _exists(inp: Inputs, relative: str) -> bool:
    return (inp.root / relative).exists()


def plain_scorer(name: str) -> str:
    return PLAIN_SCORERS.get(name, name.replace("baseline_", "").replace("_", " "))


def _sentence(text: str) -> str:
    text = text.strip()
    return text if text.endswith((".", "!", "?")) else text + "."


def _day_row(capacity: pd.DataFrame, share: str) -> pd.Series:
    return facts.one(capacity, period="final_2023", scheme="by_day", capacity=share)


# ============================================================================================ opening sections
def _opening(inp: Inputs, ev: Evidence) -> str:
    summary = inp.csv(inp.final_name(SEVERE, "summary"), required=True)
    fin = locked_scorer_row(summary)
    intro = ("This project looks at flights that land two or more hours late, and at flights that are cancelled. It asks one simple question: "
             "two hours before a flight leaves, can its schedule alone tell us which flights are more likely to be badly delayed? "
             f"These flights are rare ({pct(fin['prevalence'], 2)} of the 2023 flights in this data), so the question is hard. "
             "The project also studies how airports and routes behave when disruption builds up and when it clears, and how far the predicted probabilities can be trusted.")
    scope = f"> **Scope:** {POSITIONING} It has no API, no deployment, no streaming and no live airline data."
    return "\n\n".join([intro, scope])


def _plain_words(inp: Inputs, ev: Evidence) -> str:
    summary = inp.csv(inp.final_name(SEVERE, "summary"), required=True)
    capacity = inp.csv(inp.final_name(SEVERE, "capacity"), required=True)
    d = ev.target(SEVERE)
    failed = failed_claims(d["claims"])
    fin = locked_scorer_row(summary)
    day10 = _day_row(capacity, "10%")
    p = ev.lock["periods"]
    if not failed:
        result = (f"The model ranks severe delays better than chance and better than the strongest simple rule. Its PR-AUC is {num(fin['pr_auc'])}, "
                  f"which is {num(fin['lift'], 2)} times what a random ranking would score.")
    else:
        names = ", ".join(PLAIN_CLAIMS.get(name, name) for name in failed)
        result = (f"The model passed {3 - len(failed)} of 3 checks that were fixed in advance. It did not pass: {names}. "
                  f"Its PR-AUC is {num(fin['pr_auc'])}, which is {num(fin['lift'], 2)} times what a random ranking would score.")
    if day10["recall"] < 0.5:
        result += f" Even so, most severe delays ({pct(1 - day10['recall'], 0)}) are not in its top 10% of flights each day."
    lines = [
        f"A flight counts as **severely delayed** here if it lands 120 minutes (2 hours) or more after its planned arrival time. This line is our own choice, not an official rule. "
        f"In the 2023 test data, {pct(fin['prevalence'], 2)} of flights were severely delayed.",
        "The model sees only what is known **two hours before departure**: the planned time, the airline, the two airports and the route. It never sees what happens on the day.",
        f"We trained on flights from {p['fit']}, stopped training early using {p['early_stop']}, chose between models on {p['validation']}, "
        f"locked every choice in a sealed file, and then scored {p['final_test']} once.",
        result,
    ]
    lines.append("Cancellations: no model was selected. The baseline showed no skill over chance and did not beat the strongest history rule."
                 if not cancel_outcome_positive(ev.target(CANCEL)["claims"])
                 else "Cancellations: the plain baseline passed at least one of the first two checks. It stays a ranking-only baseline.")
    rejected = list(ev.lock.get("rejected_challengers", {}))
    if rejected:
        lines.append(f"{len(rejected)} neural-network models were tested and rejected. The simpler LightGBM model is the result, and that is a valid outcome.")
    return "\n".join(["## The project in plain words", "", bullets(lines)])


def _outcome(inp: Inputs, ev: Evidence) -> str:
    summary = inp.csv(inp.final_name(SEVERE, "summary"), required=True)
    capacity = inp.csv(inp.final_name(SEVERE, "capacity"), required=True)
    d = ev.target(SEVERE)
    fin = locked_scorer_row(summary)
    c2 = d["claims"]["C2_beats_history"]
    base = facts.one(summary, period="final_2023", scorer=c2["baseline"])
    n_features = ev.locked(SEVERE).get("n_features")
    model = "LightGBM" + (f" with {n_features} schedule, carrier, airport and route features" if n_features else "") + ", locked before 2023 was read"
    rows = [
        ("Model", model),
        ("Final test period", ev.lock["periods"]["final_test"]),
        ("Flights scored", whole(fin["rows"])),
        ("Severely delayed flights", whole(fin["events"])),
        ("Share of flights severely delayed", pct(fin["prevalence"], 2)),
        ("PR-AUC of the model", f"{num(fin['pr_auc'])} {interval(fin['pr_auc_low'], fin['pr_auc_high'])}"),
        (f"PR-AUC of the strongest simple rule ({plain_scorer(c2['baseline'])})", num(base["pr_auc"])),
        ("Lift over chance", num(fin["lift"], 2)),
    ]
    table = md_table(pd.DataFrame(rows, columns=["measure", "result"]), [("Final test measure", "measure", None), ("Result", "result", None)])
    part = _order(capacity[(capacity["period"] == "final_2023") & (capacity["scheme"] == "by_day")], "capacity", CAPACITY_ORDER)
    review = md_table(part, [
        ("Share of each day's flights reviewed", "capacity", None), ("Flights reviewed", "reviewed", whole), ("Severe delays caught", "events_captured", whole),
        ("Share of all severe delays caught", "recall", pct), ("Reviewed flights that were severely delayed", "precision", pct), ("False alerts", "false_alerts", whole),
    ])
    return "\n".join(["## Project outcome", "", "The numbers below come from the 2023 final test. The model was scored on these flights once.", "", table, "",
                      "**What-if review lists.** Each day, flights are ranked by predicted risk and the top share is flagged for review. "
                      "A false alert is a flagged flight that was not severely delayed.", "", review, "",
                      "The review lists are a what-if on past data. They show how well the ranking works. They are not airline decisions, costs or savings."])


def _words() -> str:
    return "\n".join(["## Words used in this README", "", bullets(list(GLOSSARY))])


def _questions() -> str:
    lines = [f"{i}. {question}" for i, (question, _, _) in enumerate(QUESTIONS, 1)]
    return "\n".join(["## Questions this project answers", "", *lines, "",
                      "The final technical report gives the answer to each question and names the file that holds the evidence."])


def _data(ev: Evidence, inp: Inputs) -> str:
    lines = [
        f"One source: the [Flight Delay and Cancellation Dataset 2019 to 2023]({KAGGLE_URL}) on Kaggle. The file is `data/raw/flights_kaggle/flights_sample_3m.csv`. "
        "The audit found about three million flights from 2019-01-01 to 2023-08-31.",
        "The full data are not in this repository. Raw data stay unchanged under `data/raw/`. Processed data, model files and logs are ignored by Git.",
        "Weather data were part of the first plan. The final pipeline uses flight data only, and no weather result is claimed.",
    ]
    if _exists(inp, "docs/data/source_metadata.md"):
        lines.append("The source page, access date, file hash, row counts, coverage and licence terms are in `docs/data/source_metadata.md`.")
    if _exists(inp, "docs/data/data_card.md"):
        lines.append("The data card is `docs/data/data_card.md`.")
    lines.append("The data belong to their publisher. This repository's licence does not cover them.")
    return "\n".join(["## Dataset", "", bullets(lines)])


# ============================================================================================ method
def _leakage(ev: Evidence, inp: Inputs) -> str:
    p = ev.lock["periods"]
    lines = [
        f"Prediction timestamp: {ev.lock['prediction_time']}. A feature can use only what is known by then.",
        "Left out for the flight being predicted: actual departure and arrival times, arrival delay, delay causes, whether it was cancelled, and any final-status field.",
        "Airports sit in different time zones. Local times are kept as given. An audited airport time-zone table gives UTC times for ordering. Times at two airports are never subtracted directly.",
        f"Splits follow the calendar. Fit: {p['fit']}. Early stopping: {p['early_stop']}. Validation: {p['validation']}. Final test: {p['final_test']}.",
        "Encoders, imputers, calibrators and settings are fitted only on earlier periods.",
        "The 2023 rows were not used for any choice. The model, settings, calibrator, cutoffs and pass/fail checks were fixed in a sealed lock file before 2023 was scored, and the test was run once. "
        "The 2023 event rate was known from the earlier data audit and is disclosed in the decision log. No model, calibration or policy choice used it.",
        "The source has no usable aircraft identifier, so the study does not build aircraft rotations or claim aircraft-level propagation.",
        "The years are treated as different regimes: 2019 before COVID, the 2020 shock, 2021 to 2022 recovery, and partial 2023. 2020 is kept and treated as a distribution shift.",
    ]
    if _exists(inp, "docs/data/leakage_audit.md"):
        lines.append("The full audit is in `docs/data/leakage_audit.md`.")
    return "\n".join(["### Leakage-safe evaluation", "", bullets(lines)])


def _modelling(inp: Inputs, ev: Evidence) -> str:
    summary = inp.csv(inp.final_name(SEVERE, "summary"), required=True)
    fin = locked_scorer_row(summary)
    chosen = ev.selected["rule_1"]["chosen_method"]
    names = [PLAIN_METHODS.get(m, m) for m in ev.selected["methods_compared"]]
    compared = ", ".join(names[:-1]) + " and " + names[-1] if len(names) > 1 else names[0]
    fit_period = ev.locked(SEVERE).get("calibrator_primary", {}).get("fit_period")
    gloss = METHOD_GLOSS.get(chosen, chosen)
    calibration = f"Probability calibration: these ways were compared on 2022 data: {compared}. {gloss[:1].upper() + gloss[1:]} was chosen."
    if fit_period:
        calibration += f" It was fitted on {fit_period} data and never on 2023."
    lines = [
        "Simple baselines first: the overall rate, and the past rate of each carrier, origin airport, destination airport and route. Each uses earlier rows only.",
        "Then Logistic Regression, LightGBM and XGBoost, on the same date splits and the same features. Linear, Ridge and Elastic Net models were used for arrival-delay regression.",
        f"The main score is PR-AUC, which suits rare events. Accuracy is not used. A model that always says \"not severely delayed\" would be right for {pct(1 - fin['prevalence'], 1)} of flights and find none of the delays.",
        "Also reported: precision, recall, F1, ROC-AUC, Brier score and reliability curves.",
        calibration,
        "Ranking uses the raw model score. Calibrated probabilities are used only for the probability checks.",
    ]
    return "\n".join(["### Models and calibration", "", bullets(lines)])


def _scenarios() -> str:
    lines = ["Each day, flights are ranked by predicted risk, and the top 0.5%, 1%, 5% or 10% are flagged for a what-if review.",
             "Ranking inside each day is the fair test. Ranking the whole period could just pick flights from busy seasons.",
             "Any penalty weights used in the reports are illustrative. No airline cost or saving is claimed."]
    return "\n".join(["### Review scenarios", "", bullets(lines)])


def _method(inp: Inputs, ev: Evidence) -> str:
    return "\n\n".join(["## Methodology", _leakage(ev, inp), _modelling(inp, ev), _scenarios()])


# ============================================================================================ advanced experiments, explanations, errors
def _advanced(ev: Evidence) -> str:
    rejected = ev.lock.get("rejected_challengers", {})
    lines = ["LSTM, GRU and a compact Transformer were tested on airport schedule sequences, with a plain neural network (MLP) as a control. They were tried only after the tabular pipeline was stable.",
             "The sequences use earlier schedule records only. They are not aircraft sequences, because the source has no usable aircraft identifier."]
    nested: list[str] = []
    if rejected:
        lines.append("No challenger earned a place on the 2022 evidence, so none was scored on 2023:")
        nested = [f"  - `{name}`: {_sentence(reason)}" for name, reason in rejected.items()]
    else:
        lines.append("The lock file lists no rejected challenger.")
    return "\n".join(["## Advanced experiments", "", bullets(lines), *nested])


def _explain_and_errors(inp: Inputs, ev: Evidence) -> str:
    capacity = inp.csv(inp.final_name(SEVERE, "capacity"), required=True)
    day1, day10 = _day_row(capacity, "1%"), _day_row(capacity, "10%")
    lines = []
    importance, families = inp.csv(inp.shap_name("global")), inp.csv(inp.shap_name("family"))
    if importance is not None and families is not None and len(importance) >= 3 and len(families):
        top = ", ".join(f"{r.feature} ({pct(r.share_of_total, 0)})" for r in importance.head(3).itertuples())
        lead = families.sort_values("share_of_total", ascending=False).iloc[0]
        lines.append(f"SHAP on 2022 data: the features that moved the model most were {top}. The biggest feature group was {lead['family']}, at {pct(lead['share_of_total'], 0)} of the total.")
    lines.append("SHAP shows what the model used. It does not show what caused a delay.")
    lines.append(f"Inside each day, the top 10% list leaves {whole(day10['events_missed'])} severe delays outside it and holds {whole(day10['false_alerts'])} flights that were not severely delayed.")
    lines.append(f"The top 1% list catches {whole(day1['events_captured'])} severe delays and holds {whole(day1['false_alerts'])} false alerts.")
    lines.append("A single score hides a lot. The error analysis report breaks the results down by period, carrier, airport, hour, delay size and missing data.")
    return "\n".join(["## Explainability and error analysis", "", bullets(lines)])


def _results(inp: Inputs, ev: Evidence) -> str:
    summary = inp.csv(inp.final_name(SEVERE, "summary"), required=True)
    calibration = inp.csv(inp.final_name(SEVERE, "calibration"), required=True)
    fin = summary[summary["period"] == "final_2023"].copy()
    fin["interval_text"] = [interval(l, h) for l, h in zip(fin["pr_auc_low"], fin["pr_auc_high"])]
    fin["scorer_name"] = [plain_scorer(s) if s.startswith("baseline_") else "LightGBM (locked model)" for s in fin["scorer"]]
    locked = calibration[calibration["variant"].str.contains("locked primary")]
    r22, r23 = facts.one(locked, period="validation_2022"), facts.one(locked, period="final_2023")
    prev22 = facts.one(summary, period="validation_2022", scorer="lightgbm_locked")["prevalence"]
    prev23 = facts.one(summary, period="final_2023", scorer="lightgbm_locked")["prevalence"]
    line = (f"Calibration: the ratio of predicted to observed severe delays was {num(r22['predicted_to_observed'], 3)} on 2022 and {num(r23['predicted_to_observed'], 3)} on 2023. "
            "A ratio of 1 is perfect.")
    if r23["predicted_to_observed"] < r22["predicted_to_observed"] and prev23 > prev22:
        line += (f" The severe-delay rate rose from {pct(prev22, 2)} to {pct(prev23, 2)}, so the probabilities were too low in 2023. "
                 "A fixed probability cutoff is not stable when the event rate moves.")
    parts = ["## Results in more detail", "", "**Severe arrival delay (120 minutes or more), 2023 final test, scored once.**", "",
             md_table(fin, [("Scorer", "scorer_name", None), ("PR-AUC", "pr_auc", num), ("95% interval", "interval_text", None), ("Lift", "lift", lambda v: num(v, 2)),
                            ("ROC-AUC", "roc_auc", lambda v: num(v, 3))]), "", line, "",
             "**Regression, recovery and network.** Arrival-delay regression models were checked on validation data only. No regression model was locked, so none was scored on 2023. "
             "Airport recovery, network and association results are in the reports listed below."]
    return "\n".join(parts)


# ============================================================================================ repository, reports, reproduction
def _layout(inp: Inputs) -> str:
    # reports/evaluation/ is written by the same run, so it counts as present even on a fresh checkout.
    present = [(path, why) for path, why in LAYOUT if path == "reports/evaluation/" or _exists(inp, path)]
    present.append(("data/", "Raw and processed data. Not in Git"))
    width = max(len(path) for path, _ in present)
    tree = [f"{REPO_NAME}/"]
    for i, (path, why) in enumerate(present):
        branch = "\u2514\u2500\u2500 " if i == len(present) - 1 else "\u251c\u2500\u2500 "
        tree.append(f"{branch}{path.ljust(width)}  # {why}")
    return "\n".join(["## Repository structure", "", "```text", *tree, "```"])


def _reports(inp: Inputs) -> str:
    found = [(name, why) for name, why in REPORTS if name in BUILT_HERE or _exists(inp, f"reports/evaluation/{name}")]
    return "\n".join(["## Key reports", "", bullets([f"[`reports/evaluation/{name}`](reports/evaluation/{name}): {why}" for name, why in found])])


def _figures(inp: Inputs) -> str:
    shown = [(name, alt) for name, alt in FIGURES if _exists(inp, f"reports/figures/{name}")]
    if not shown:
        return ""
    return "\n\n".join(["## Figures"] + [f"![{alt}](reports/figures/{name})" for name, alt in shown])


def _reproduce(ev: Evidence) -> str:
    python = ev.decision.get("hardware", {}).get("python")
    env = "The package and its dependencies are defined in `pyproject.toml`."
    if python:
        env += f" The final test ran on Python {python}."
    return "\n".join([
        "## Reproducibility", "", "### 1. Environment (Windows PowerShell)", "",
        "```powershell", "python -m venv .venv", r".\.venv\Scripts\Activate.ps1", "pip install -e .", "```", "",
        env + " On macOS or Linux, activate with `source .venv/bin/activate`.", "",
        "### 2. Get the data", "",
        f"Download the flight file from [Kaggle]({KAGGLE_URL}) and place it at `data/raw/flights_kaggle/flights_sample_3m.csv`. Do not edit it. Raw data are never committed.", "",
        "### 3. Run the tests", "", "```powershell", "python -m pytest -q", "```", "",
        "### 4. Rebuild the final steps", "",
        "```powershell", "python scripts/run_phase7a_explain_and_errors.py", "python scripts/run_phase7b_final_lock.py",
        "python scripts/run_phase7b_final_test.py --confirm USE-2023-ONCE", "python scripts/build_phase7_reports.py", "```", "",
        "The final test step is meant to run once. A rerun must reproduce the stored scores.", "",
        "Before committing, run `python scripts/check_repo_hygiene.py`. It refuses data, model files, test outputs and credentials.",
    ])


# ============================================================================================ limits, claim, licence
def _limits(inp: Inputs, ev: Evidence) -> str:
    lines = [_sentence(text[:1].upper() + text[1:]) for text in ev.decision.get("limits", [])]
    lines += ["The model uses the schedule only. It cannot see an airport's state on the day, so it cannot see disruption building up before the prediction time.",
              "Results are associations in past data. They do not say why a flight was late or what an airline could have done.",
              "The review scenarios use illustrative weights. They are not airline costs or operating decisions."]
    if _exists(inp, "docs/decisions/limitations_and_appropriate_use.md"):
        lines.append("Scope and appropriate use are set out in `docs/decisions/limitations_and_appropriate_use.md`.")
    not_supported = [f"- {item[:1].upper() + item[1:]}" for item in NOT_SUPPORTED]
    return "\n".join(["## Limitations", "", bullets(lines), "", "The evidence does not support:", "", "\n".join(not_supported)])


def _claim(ev: Evidence) -> str:
    text = ("This project tests flight-level disruption prediction using date-based validation, features known two hours before departure, calibrated probabilities, "
            "a sealed once-only final test, airport and route network analysis, airport-level recovery analysis, sequence-model challengers, SHAP explanations, "
            "error analysis and what-if review lists.")
    if ev.lock.get("rejected_challengers"):
        text += " The simpler tabular model won, and the evidence for that is in the reports."
    return "\n".join(["## Portfolio claim", "", text])


def _licence(inp: Inputs) -> str:
    if _exists(inp, "LICENSE"):
        text = "Code is released under the licence in `LICENSE`. It does not relicense the third-party flight data."
    else:
        text = "No licence file has been chosen yet. The flight data are third-party and are not covered by any licence for this code."
    if _exists(inp, "CITATION.cff"):
        text += " Citation details are in `CITATION.cff`."
    return "\n".join(["## Licence", "", text])


def build(inp: Inputs, ev: Evidence) -> str:
    smoke = "> **TEST BUILD from smoke tables. The numbers are not results.**" if ev.smoke else ""
    return join_sections([
        f"{MARKER}\n# {PROJECT_TITLE}", smoke, _opening(inp, ev), _plain_words(inp, ev), _outcome(inp, ev), _words(), _questions(), _data(ev, inp),
        _method(inp, ev), _advanced(ev), _explain_and_errors(inp, ev), _results(inp, ev), _layout(inp), _reports(inp), _figures(inp),
        _reproduce(ev), _limits(inp, ev), _claim(ev), _licence(inp),
    ])
