#!/usr/bin/env python
"""Phase 7, Steps 13 and 14: build the five written reports from the result tables.

Save as:   scripts/build_phase7_reports.py
Run from the project root, after the final test has been run:

    python scripts/build_phase7_reports.py

Writes
------
    reports/evaluation/calibration_and_alert_policy_report.md
    reports/evaluation/explainability_report.md
    reports/evaluation/error_analysis_report.md
    reports/evaluation/final_model_selection_report.md
    reports/evaluation/final_technical_report.md
    README.md                                        (or README.generated.md if a hand-written README.md exists)
    reports/tables/phase7_reports_manifest.json      (every input file and its SHA-256)

Nothing is typed in by hand. Every number is read from a table that an earlier step wrote, so a report cannot drift from
its CSV. The script stops if the lock hash in the final decision, the lock file and the consumed marker disagree, because then
the tables are not from one locked test.

It reads tables only. It loads no flight data and trains nothing, and it takes a few seconds.

For a test build on smoke tables:  --tag smoke --lock reports/final/final_protocol_lock_smoke.json
A test build writes files with the tag in their names and a banner saying the numbers are not results.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
try:
    from airline_disruption.reporting import calibration_report, error_report, explain_report, readme_report, selection_report, technical_report
    from airline_disruption.reporting.common import load_evidence
    from airline_disruption.reporting.inputs import LOCK_PATH, Inputs, MissingInput
    from airline_disruption.reporting.text import check_clean
except ImportError:  # package not installed in editable mode: fall back to the src folder
    sys.path.insert(0, str(ROOT / "src"))
    from airline_disruption.reporting import calibration_report, error_report, explain_report, readme_report, selection_report, technical_report  # noqa: E402
    from airline_disruption.reporting.common import load_evidence  # noqa: E402
    from airline_disruption.reporting.inputs import LOCK_PATH, Inputs, MissingInput  # noqa: E402
    from airline_disruption.reporting.text import check_clean  # noqa: E402

REPORTS = (
    ("calibration_and_alert_policy_report", calibration_report),
    ("explainability_report", explain_report),
    ("error_analysis_report", error_report),
    ("final_model_selection_report", selection_report),
    ("final_technical_report", technical_report),
)


def write_readme(root: Path, text: str, smoke: bool) -> Path:
    """Write the README without ever overwriting one that a person wrote.

    A README that starts with the generated marker (or does not exist) is replaced. A hand-written one is left alone and the new text
    goes to README.generated.md, so the two can be compared and merged by hand. A test build never touches README.md.
    """
    target = root / "README.md"
    if smoke:
        path = root / "README_smoke.md"
    elif target.exists() and readme_report.MARKER not in target.read_text(encoding="utf-8", errors="ignore")[:200]:
        path = root / "README.generated.md"
        print("  README.md already exists and was not generated by this script, so it was left alone.")
    else:
        path = target
    path.write_text(text, encoding="utf-8")
    print(f"  wrote {path.relative_to(root)} ({len(text.splitlines())} lines)")
    return path


def main() -> int:
    parser = argparse.ArgumentParser(description="Phase 7 written reports from the result tables")
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--tag", default="", help="file-name tag of the Step 10 and Step 11 tables (test builds only)")
    parser.add_argument("--lock", default=LOCK_PATH, help="lock file (a smoke lock for test builds)")
    args = parser.parse_args()
    root = args.root.resolve()

    inp = Inputs(root=root, tag=args.tag, lock_path=args.lock)
    try:
        evidence = load_evidence(inp)
    except MissingInput as problem:
        print(f"\nCHECK FAILED: {problem}")
        print("Run scripts/run_phase7b_final_test.py first (once), then this script.")
        return 1

    out_dir = root / "reports/evaluation"
    # A smoke lock can never write the real file names, even if --tag was forgotten.
    infix = f"_{args.tag}" if args.tag else ("_smoke" if evidence.smoke else "")
    texts = {}
    for name, module in REPORTS:       # build all five first, so a failure leaves no half-written set
        try:
            texts[name] = check_clean(module.build(inp, evidence), name)
        except (MissingInput, ValueError, KeyError) as problem:
            print(f"\nCHECK FAILED while building {name}: {problem}")
            print("No report was written.")
            return 1
    try:
        readme_text = check_clean(readme_report.build(inp, evidence), "README")
    except (MissingInput, ValueError, KeyError) as problem:
        print(f"\nCHECK FAILED while building the README: {problem}")
        print("No report was written.")
        return 1
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name, text in texts.items():
        path = out_dir / f"{name}{infix}.md"
        path.write_text(text, encoding="utf-8")
        written.append(str(path.relative_to(root)))
        print(f"  wrote {path.relative_to(root)} ({len(text.splitlines())} lines)")

    readme_path = write_readme(root, readme_text, smoke=bool(infix))
    written.append(str(readme_path.relative_to(root)))

    manifest = {
        "created_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"), "tag": args.tag, "smoke": evidence.smoke,
        "lock_sha256": evidence.lock_sha, "first_run_utc": evidence.marker.get("first_run_utc"),
        "reports": written, "inputs": dict(sorted(inp.used.items())), "missing_inputs": sorted(inp.missing),
    }
    manifest_path = root / "reports/tables" / f"phase7_reports_manifest{infix}.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"  wrote {manifest_path.relative_to(root)} ({len(inp.used)} inputs, {len(inp.missing)} not found)")
    if inp.missing:
        print("\nNot found (the report says so in its last section):")
        for path in sorted(inp.missing):
            print(f"  {path}")
    print("\nReports are built from tables only. No flight data was loaded.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
